#+title: React & Vite Project 04

* React + Vite
This template provides a minimal setup to get React working in Vite with HMR and some ESLint rules.

Currently, two official plugins are available:

- [[https://github.com/vitejs/vite-plugin-react/blob/main/packages/plugin-react/README.md][vitejs/plugin-react]] uses [[https://babeljs.io/][Babel]] for Fast Refresh
- [[https://github.com/vitejs/vite-plugin-react-swc][vitejs/plugin-react-swc]] uses [[https://swc.rs/][SWC]] for Fast Refresh

* Create the Project
+ The following command is going to create the project.
+ Then just answer the different questions generated by the script to complete the process of creation
#+begin_src bash
npm init vite@latest
#+end_src

* Start the Server
#+begin_src bash
npm run dev
#+end_src

* TailwindCSS
** Installation
#+begin_src bash
npm i -D tailwindcss postcss autoprefixer
#+end_src
** Configuration
*** Step 01
The following command will create two config files: tailwind.config.js and postcss.config.js
#+begin_src bash
npx tailwindcss init -p
#+end_src
*** Step 02
Look for the file src/index.css that was created by vite and add the following commands
#+begin_src css
@tailwind base;
@tailwind components;
@tailwind utilities;
#+end_src
*** Step 03
Open the file named tailwind.config.js that was created in the first step, and change it with the following content
#+begin_src js
/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {},
  },
  plugins: [],
}
#+end_src

* Dependencies
** React Router Dom
The previews projects were a single page website that according with certain logics it was decided the components that were shown to the user. Moreover, in projects that are a bit more medium or large size, it is a good practice to use a routing library in order to have several pages for a website. That way, it is going to be easier to keep a cleaner code and structure.
There are several alternatives but for this project, it was decided to use react-router-dom
#+begin_src bash
npm install react-router-dom
#+end_src
* Deployment
